const CardsConfig = [
    { id: 1, path: '/cards/card-blue-1.png', },
    { id: 2, path: '/cards/card-blue-2.png', },
    { id: 3, path: '/cards/card-blue-3.png', },
    { id: 4, path: '/cards/card-blue-4.png', },
    { id: 5, path: '/cards/card-blue-5.png', },
    { id: 6, path: '/cards/card-pink-1.png', },
    { id: 7, path: '/cards/card-pink-2.png', },
    { id: 8, path: '/cards/card-pink-3.png', },
    { id: 9, path: '/cards/card-pink-4.png', },
    { id: 10, path: '/cards/card-pink-5.png', },
    { id: 11, path: '/cards/card-pink-6.png', },
    { id: 12, path: '/cards/card-yellow-1.png', },
    { id: 13, path: '/cards/card-yellow-2.png', },
    { id: 14, path: '/cards/card-yellow-3.png', },
    { id: 15, path: '/cards/card-yellow-4.png', },
    { id: 16, path: '/cards/card-yellow-5.png', },
    { id: 17, path: '/cards/card-yellow-6.png', },
    { id: 18, path: '/cards/golden-ticket-1.png', },
    { id: 19, path: '/cards/golden-ticket-2.png', },
    { id: 20, path: '/cards/instant-wins-1.png', },
    { id: 21, path: '/cards/instant-wins-2.png', },
    { id: 22, path: '/cards/instant-wins-3.png', },
    { id: 23, path: '/cards/xp-1.png', },
    { id: 24, path: '/cards/xp-2.png', },
    { id: 25, path: '/cards/xp-3.png', },
    { id: 26, path: '/cards/xp-4.png', },
];

export default CardsConfig;
