const CardsConfig = [
    { id: 1, path: '../assets/card-blue-1.png', },
    { id: 2, path: '../assets/card-blue-2.png', },
    { id: 3, path: '../assets/card-blue-3.png', },
    { id: 4, path: '../assets/card-blue-4.png', },
    { id: 5, path: '../assets/card-blue-5.png', },
    { id: 6, path: '../assets/card-pink-1.png', },
    { id: 7, path: '../assets/card-pink-2.png', },
    { id: 8, path: '../assets/card-pink-3.png', },
    { id: 9, path: '../assets/card-pink-4.png', },
    { id: 10, path: '../assets/card-pink-5.png', },
    { id: 11, path: '../assets/card-pink-6.png', },
    { id: 12, path: '../assets/card-yellow-1.png', },
    { id: 13, path: '../assets/card-yellow-2.png', },
    { id: 14, path: '../assets/card-yellow-3.png', },
    { id: 15, path: '../assets/card-yellow-4.png', },
    { id: 16, path: '../assets/card-yellow-5.png', },
    { id: 17, path: '../assets/card-yellow-6.png', },
    { id: 18, path: '../assets/golden-ticket-1.png', },
    { id: 19, path: '../assets/golden-ticket-2.png', },
    { id: 20, path: '../assets/instant-wins-1.png', },
    { id: 21, path: '../assets/instant-wins-2.png', },
    { id: 22, path: '../assets/instant-wins-3.png', },
    { id: 23, path: '../assets/xp-1.png', },
    { id: 24, path: '../assets/xp-2.png', },
    { id: 24, path: '../assets/xp-3.png', },
    { id: 25, path: '../assets/xp-4.png', },
];

export default CardsConfig;
