const CardsConfig = [
    { id: 1, path: '../assets/card-1.webp', },
    { id: 2, path: '../assets/card-2.webp', },
    { id: 3, path: '../assets/card-3.webp', },
    { id: 4, path: '../assets/card-4.webp', },
    { id: 5, path: '../assets/card-5.webp', },
    { id: 6, path: '../assets/card-6.webp', },
    { id: 7, path: '../assets/card-7.webp', },
    { id: 8, path: '../assets/card-8.webp', },
    { id: 9, path: '../assets/card-9.webp', },
    { id: 10, path: '../assets/card-10.webp', },
    { id: 11, path: '../assets/card-11.webp', },
    { id: 12, path: '../assets/card-12.webp', },
    { id: 13, path: '../assets/card-13.webp', },
    { id: 14, path: '../assets/card-14.webp', },
    { id: 15, path: '../assets/card-15.webp', },
    { id: 16, path: '../assets/card-16.webp', },
    { id: 17, path: '../assets/card-17.webp', },
    { id: 18, path: '../assets/card-18.webp', },
    { id: 19, path: '../assets/card-19.webp', },
    { id: 20, path: '../assets/card-20.webp', },
    { id: 21, path: '../assets/card-21.webp', },
    { id: 22, path: '../assets/card-22.webp', },
    { id: 23, path: '../assets/card-23.webp', },
    { id: 24, path: '../assets/card-24.webp', },
    { id: 25, path: '../assets/card-25.webp', },
    { id: 26, path: '../assets/card-26.webp', },
];

export default CardsConfig;
